//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model1", "ProductSale_Customer", "Customer", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(IremEczOtomasyonu.BL.Customer), "ProductSale", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IremEczOtomasyonu.BL.ProductSale), true)]
[assembly: EdmRelationshipAttribute("Model1", "ExpirationDate_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IremEczOtomasyonu.BL.Product), "ExpirationDate", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IremEczOtomasyonu.BL.ExpirationDate), true)]
[assembly: EdmRelationshipAttribute("Model1", "ProductPurchase_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IremEczOtomasyonu.BL.Product), "ProductPurchas", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IremEczOtomasyonu.BL.ProductPurchase), true)]
[assembly: EdmRelationshipAttribute("Model1", "SaleItem_Product", "Product", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IremEczOtomasyonu.BL.Product), "SaleItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IremEczOtomasyonu.BL.SaleItem), true)]
[assembly: EdmRelationshipAttribute("Model1", "SaleItem_ProductSale", "ProductSale", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(IremEczOtomasyonu.BL.ProductSale), "SaleItem", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(IremEczOtomasyonu.BL.SaleItem), true)]

#endregion

namespace IremEczOtomasyonu.BL
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Model1Container : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new Model1Container object using the connection string found in the 'Model1Container' section of the application configuration file.
        /// </summary>
        public Model1Container() : base("name=Model1Container", "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(string connectionString) : base(connectionString, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new Model1Container object.
        /// </summary>
        public Model1Container(EntityConnection connection) : base(connection, "Model1Container")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Customer> Customers
        {
            get
            {
                if ((_Customers == null))
                {
                    _Customers = base.CreateObjectSet<Customer>("Customers");
                }
                return _Customers;
            }
        }
        private ObjectSet<Customer> _Customers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ExpirationDate> ExpirationDates
        {
            get
            {
                if ((_ExpirationDates == null))
                {
                    _ExpirationDates = base.CreateObjectSet<ExpirationDate>("ExpirationDates");
                }
                return _ExpirationDates;
            }
        }
        private ObjectSet<ExpirationDate> _ExpirationDates;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductPurchase> ProductPurchases
        {
            get
            {
                if ((_ProductPurchases == null))
                {
                    _ProductPurchases = base.CreateObjectSet<ProductPurchase>("ProductPurchases");
                }
                return _ProductPurchases;
            }
        }
        private ObjectSet<ProductPurchase> _ProductPurchases;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Product> Products
        {
            get
            {
                if ((_Products == null))
                {
                    _Products = base.CreateObjectSet<Product>("Products");
                }
                return _Products;
            }
        }
        private ObjectSet<Product> _Products;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<ProductSale> ProductSales
        {
            get
            {
                if ((_ProductSales == null))
                {
                    _ProductSales = base.CreateObjectSet<ProductSale>("ProductSales");
                }
                return _ProductSales;
            }
        }
        private ObjectSet<ProductSale> _ProductSales;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<SaleItem> SaleItems
        {
            get
            {
                if ((_SaleItems == null))
                {
                    _SaleItems = base.CreateObjectSet<SaleItem>("SaleItems");
                }
                return _SaleItems;
            }
        }
        private ObjectSet<SaleItem> _SaleItems;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Customers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToCustomers(Customer customer)
        {
            base.AddObject("Customers", customer);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ExpirationDates EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToExpirationDates(ExpirationDate expirationDate)
        {
            base.AddObject("ExpirationDates", expirationDate);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductPurchases EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductPurchases(ProductPurchase productPurchase)
        {
            base.AddObject("ProductPurchases", productPurchase);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Products EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProducts(Product product)
        {
            base.AddObject("Products", product);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the ProductSales EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToProductSales(ProductSale productSale)
        {
            base.AddObject("ProductSales", productSale);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the SaleItems EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToSaleItems(SaleItem saleItem)
        {
            base.AddObject("SaleItems", saleItem);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Customer")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Customer : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Customer object.
        /// </summary>
        /// <param name="id">Initial value of the Id property.</param>
        public static Customer CreateCustomer(global::System.Guid id)
        {
            Customer customer = new Customer();
            customer.Id = id;
            return customer;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FirstName
        {
            get
            {
                return _FirstName;
            }
            set
            {
                OnFirstNameChanging(value);
                ReportPropertyChanging("FirstName");
                _FirstName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FirstName");
                OnFirstNameChanged();
            }
        }
        private global::System.String _FirstName;
        partial void OnFirstNameChanging(global::System.String value);
        partial void OnFirstNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LastName
        {
            get
            {
                return _LastName;
            }
            set
            {
                OnLastNameChanging(value);
                ReportPropertyChanging("LastName");
                _LastName = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LastName");
                OnLastNameChanged();
            }
        }
        private global::System.String _LastName;
        partial void OnLastNameChanging(global::System.String value);
        partial void OnLastNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Birthday
        {
            get
            {
                return _Birthday;
            }
            set
            {
                OnBirthdayChanging(value);
                ReportPropertyChanging("Birthday");
                _Birthday = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Birthday");
                OnBirthdayChanged();
            }
        }
        private Nullable<global::System.DateTime> _Birthday;
        partial void OnBirthdayChanging(Nullable<global::System.DateTime> value);
        partial void OnBirthdayChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SkinType
        {
            get
            {
                return _SkinType;
            }
            set
            {
                OnSkinTypeChanging(value);
                ReportPropertyChanging("SkinType");
                _SkinType = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SkinType");
                OnSkinTypeChanged();
            }
        }
        private global::System.String _SkinType;
        partial void OnSkinTypeChanging(global::System.String value);
        partial void OnSkinTypeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MaritalStatus
        {
            get
            {
                return _MaritalStatus;
            }
            set
            {
                OnMaritalStatusChanging(value);
                ReportPropertyChanging("MaritalStatus");
                _MaritalStatus = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MaritalStatus");
                OnMaritalStatusChanged();
            }
        }
        private global::System.String _MaritalStatus;
        partial void OnMaritalStatusChanging(global::System.String value);
        partial void OnMaritalStatusChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Job
        {
            get
            {
                return _Job;
            }
            set
            {
                OnJobChanging(value);
                ReportPropertyChanging("Job");
                _Job = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Job");
                OnJobChanged();
            }
        }
        private global::System.String _Job;
        partial void OnJobChanging(global::System.String value);
        partial void OnJobChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DetailedInfo
        {
            get
            {
                return _DetailedInfo;
            }
            set
            {
                OnDetailedInfoChanging(value);
                ReportPropertyChanging("DetailedInfo");
                _DetailedInfo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DetailedInfo");
                OnDetailedInfoChanged();
            }
        }
        private global::System.String _DetailedInfo;
        partial void OnDetailedInfoChanging(global::System.String value);
        partial void OnDetailedInfoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] Photo
        {
            get
            {
                return StructuralObject.GetValidValue(_Photo);
            }
            set
            {
                OnPhotoChanging(value);
                ReportPropertyChanging("Photo");
                _Photo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Photo");
                OnPhotoChanged();
            }
        }
        private global::System.Byte[] _Photo;
        partial void OnPhotoChanging(global::System.Byte[] value);
        partial void OnPhotoChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneHome
        {
            get
            {
                return _PhoneHome;
            }
            set
            {
                OnPhoneHomeChanging(value);
                ReportPropertyChanging("PhoneHome");
                _PhoneHome = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneHome");
                OnPhoneHomeChanged();
            }
        }
        private global::System.String _PhoneHome;
        partial void OnPhoneHomeChanging(global::System.String value);
        partial void OnPhoneHomeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PhoneMobile
        {
            get
            {
                return _PhoneMobile;
            }
            set
            {
                OnPhoneMobileChanging(value);
                ReportPropertyChanging("PhoneMobile");
                _PhoneMobile = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("PhoneMobile");
                OnPhoneMobileChanged();
            }
        }
        private global::System.String _PhoneMobile;
        partial void OnPhoneMobileChanging(global::System.String value);
        partial void OnPhoneMobileChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ProductSale_Customer", "ProductSale")]
        public EntityCollection<ProductSale> ProductSales
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProductSale>("Model1.ProductSale_Customer", "ProductSale");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProductSale>("Model1.ProductSale_Customer", "ProductSale", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ExpirationDate")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ExpirationDate : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ExpirationDate object.
        /// </summary>
        /// <param name="exDate">Initial value of the ExDate property.</param>
        /// <param name="numItems">Initial value of the NumItems property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        public static ExpirationDate CreateExpirationDate(global::System.DateTime exDate, global::System.Int32 numItems, global::System.Guid id, global::System.Guid productId)
        {
            ExpirationDate expirationDate = new ExpirationDate();
            expirationDate.ExDate = exDate;
            expirationDate.NumItems = numItems;
            expirationDate.Id = id;
            expirationDate.ProductId = productId;
            return expirationDate;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExDate
        {
            get
            {
                return _ExDate;
            }
            set
            {
                OnExDateChanging(value);
                ReportPropertyChanging("ExDate");
                _ExDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExDate");
                OnExDateChanged();
            }
        }
        private global::System.DateTime _ExDate;
        partial void OnExDateChanging(global::System.DateTime value);
        partial void OnExDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumItems
        {
            get
            {
                return _NumItems;
            }
            set
            {
                OnNumItemsChanging(value);
                ReportPropertyChanging("NumItems");
                _NumItems = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumItems");
                OnNumItemsChanged();
            }
        }
        private global::System.Int32 _NumItems;
        partial void OnNumItemsChanging(global::System.Int32 value);
        partial void OnNumItemsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ExpirationDate_Product", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.ExpirationDate_Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.ExpirationDate_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.ExpirationDate_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Model1.ExpirationDate_Product", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="Product")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Product : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Product object.
        /// </summary>
        /// <param name="numItems">Initial value of the NumItems property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static Product CreateProduct(global::System.Int32 numItems, global::System.Guid id)
        {
            Product product = new Product();
            product.NumItems = numItems;
            product.Id = id;
            return product;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Barcode
        {
            get
            {
                return _Barcode;
            }
            set
            {
                OnBarcodeChanging(value);
                ReportPropertyChanging("Barcode");
                _Barcode = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Barcode");
                OnBarcodeChanged();
            }
        }
        private global::System.String _Barcode;
        partial void OnBarcodeChanging(global::System.String value);
        partial void OnBarcodeChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Name
        {
            get
            {
                return _Name;
            }
            set
            {
                OnNameChanging(value);
                ReportPropertyChanging("Name");
                _Name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Name");
                OnNameChanged();
            }
        }
        private global::System.String _Name;
        partial void OnNameChanging(global::System.String value);
        partial void OnNameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Brand
        {
            get
            {
                return _Brand;
            }
            set
            {
                OnBrandChanging(value);
                ReportPropertyChanging("Brand");
                _Brand = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Brand");
                OnBrandChanged();
            }
        }
        private global::System.String _Brand;
        partial void OnBrandChanging(global::System.String value);
        partial void OnBrandChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumItems
        {
            get
            {
                return _NumItems;
            }
            set
            {
                OnNumItemsChanging(value);
                ReportPropertyChanging("NumItems");
                _NumItems = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumItems");
                OnNumItemsChanged();
            }
        }
        private global::System.Int32 _NumItems;
        partial void OnNumItemsChanging(global::System.Int32 value);
        partial void OnNumItemsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentBuyingPrice
        {
            get
            {
                return _CurrentBuyingPrice;
            }
            set
            {
                OnCurrentBuyingPriceChanging(value);
                ReportPropertyChanging("CurrentBuyingPrice");
                _CurrentBuyingPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentBuyingPrice");
                OnCurrentBuyingPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentBuyingPrice;
        partial void OnCurrentBuyingPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentBuyingPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CurrentSellingPrice
        {
            get
            {
                return _CurrentSellingPrice;
            }
            set
            {
                OnCurrentSellingPriceChanging(value);
                ReportPropertyChanging("CurrentSellingPrice");
                _CurrentSellingPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CurrentSellingPrice");
                OnCurrentSellingPriceChanged();
            }
        }
        private Nullable<global::System.Decimal> _CurrentSellingPrice;
        partial void OnCurrentSellingPriceChanging(Nullable<global::System.Decimal> value);
        partial void OnCurrentSellingPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ExpirationDate_Product", "ExpirationDate")]
        public EntityCollection<ExpirationDate> ExpirationDates
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ExpirationDate>("Model1.ExpirationDate_Product", "ExpirationDate");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ExpirationDate>("Model1.ExpirationDate_Product", "ExpirationDate", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ProductPurchase_Product", "ProductPurchas")]
        public EntityCollection<ProductPurchase> ProductPurchases
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<ProductPurchase>("Model1.ProductPurchase_Product", "ProductPurchas");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<ProductPurchase>("Model1.ProductPurchase_Product", "ProductPurchas", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SaleItem_Product", "SaleItem")]
        public EntityCollection<SaleItem> SaleItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SaleItem>("Model1.SaleItem_Product", "SaleItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SaleItem>("Model1.SaleItem_Product", "SaleItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ProductPurchase")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductPurchase : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductPurchase object.
        /// </summary>
        /// <param name="price">Initial value of the Price property.</param>
        /// <param name="purchaseDate">Initial value of the PurchaseDate property.</param>
        /// <param name="numItems">Initial value of the NumItems property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="exDate">Initial value of the ExDate property.</param>
        public static ProductPurchase CreateProductPurchase(global::System.Decimal price, global::System.DateTime purchaseDate, global::System.Int32 numItems, global::System.Guid id, global::System.Guid productId, global::System.DateTime exDate)
        {
            ProductPurchase productPurchase = new ProductPurchase();
            productPurchase.Price = price;
            productPurchase.PurchaseDate = purchaseDate;
            productPurchase.NumItems = numItems;
            productPurchase.Id = id;
            productPurchase.ProductId = productId;
            productPurchase.ExDate = exDate;
            return productPurchase;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal Price
        {
            get
            {
                return _Price;
            }
            set
            {
                OnPriceChanging(value);
                ReportPropertyChanging("Price");
                _Price = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Price");
                OnPriceChanged();
            }
        }
        private global::System.Decimal _Price;
        partial void OnPriceChanging(global::System.Decimal value);
        partial void OnPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime PurchaseDate
        {
            get
            {
                return _PurchaseDate;
            }
            set
            {
                OnPurchaseDateChanging(value);
                ReportPropertyChanging("PurchaseDate");
                _PurchaseDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PurchaseDate");
                OnPurchaseDateChanged();
            }
        }
        private global::System.DateTime _PurchaseDate;
        partial void OnPurchaseDateChanging(global::System.DateTime value);
        partial void OnPurchaseDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumItems
        {
            get
            {
                return _NumItems;
            }
            set
            {
                OnNumItemsChanging(value);
                ReportPropertyChanging("NumItems");
                _NumItems = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumItems");
                OnNumItemsChanged();
            }
        }
        private global::System.Int32 _NumItems;
        partial void OnNumItemsChanging(global::System.Int32 value);
        partial void OnNumItemsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExDate
        {
            get
            {
                return _ExDate;
            }
            set
            {
                OnExDateChanging(value);
                ReportPropertyChanging("ExDate");
                _ExDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExDate");
                OnExDateChanged();
            }
        }
        private global::System.DateTime _ExDate;
        partial void OnExDateChanging(global::System.DateTime value);
        partial void OnExDateChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ProductPurchase_Product", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.ProductPurchase_Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.ProductPurchase_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.ProductPurchase_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Model1.ProductPurchase_Product", "Product", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="ProductSale")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class ProductSale : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new ProductSale object.
        /// </summary>
        /// <param name="saleDate">Initial value of the SaleDate property.</param>
        /// <param name="totalPrice">Initial value of the TotalPrice property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        public static ProductSale CreateProductSale(global::System.DateTime saleDate, global::System.Decimal totalPrice, global::System.Guid id)
        {
            ProductSale productSale = new ProductSale();
            productSale.SaleDate = saleDate;
            productSale.TotalPrice = totalPrice;
            productSale.Id = id;
            return productSale;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime SaleDate
        {
            get
            {
                return _SaleDate;
            }
            set
            {
                OnSaleDateChanging(value);
                ReportPropertyChanging("SaleDate");
                _SaleDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SaleDate");
                OnSaleDateChanged();
            }
        }
        private global::System.DateTime _SaleDate;
        partial void OnSaleDateChanging(global::System.DateTime value);
        partial void OnSaleDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal TotalPrice
        {
            get
            {
                return _TotalPrice;
            }
            set
            {
                OnTotalPriceChanging(value);
                ReportPropertyChanging("TotalPrice");
                _TotalPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TotalPrice");
                OnTotalPriceChanged();
            }
        }
        private global::System.Decimal _TotalPrice;
        partial void OnTotalPriceChanging(global::System.Decimal value);
        partial void OnTotalPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Remarks
        {
            get
            {
                return _Remarks;
            }
            set
            {
                OnRemarksChanging(value);
                ReportPropertyChanging("Remarks");
                _Remarks = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Remarks");
                OnRemarksChanged();
            }
        }
        private global::System.String _Remarks;
        partial void OnRemarksChanging(global::System.String value);
        partial void OnRemarksChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Guid> CustomerId
        {
            get
            {
                return _CustomerId;
            }
            set
            {
                OnCustomerIdChanging(value);
                ReportPropertyChanging("CustomerId");
                _CustomerId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CustomerId");
                OnCustomerIdChanged();
            }
        }
        private Nullable<global::System.Guid> _CustomerId;
        partial void OnCustomerIdChanging(Nullable<global::System.Guid> value);
        partial void OnCustomerIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "ProductSale_Customer", "Customer")]
        public Customer Customer
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("Model1.ProductSale_Customer", "Customer").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("Model1.ProductSale_Customer", "Customer").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Customer> CustomerReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Customer>("Model1.ProductSale_Customer", "Customer");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Customer>("Model1.ProductSale_Customer", "Customer", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SaleItem_ProductSale", "SaleItem")]
        public EntityCollection<SaleItem> SaleItems
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<SaleItem>("Model1.SaleItem_ProductSale", "SaleItem");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<SaleItem>("Model1.SaleItem_ProductSale", "SaleItem", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="Model1", Name="SaleItem")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class SaleItem : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new SaleItem object.
        /// </summary>
        /// <param name="numSold">Initial value of the NumSold property.</param>
        /// <param name="exDate">Initial value of the ExDate property.</param>
        /// <param name="unitPrice">Initial value of the UnitPrice property.</param>
        /// <param name="id">Initial value of the Id property.</param>
        /// <param name="productId">Initial value of the ProductId property.</param>
        /// <param name="productSaleId">Initial value of the ProductSaleId property.</param>
        public static SaleItem CreateSaleItem(global::System.Int32 numSold, global::System.DateTime exDate, global::System.Decimal unitPrice, global::System.Guid id, global::System.Guid productId, global::System.Guid productSaleId)
        {
            SaleItem saleItem = new SaleItem();
            saleItem.NumSold = numSold;
            saleItem.ExDate = exDate;
            saleItem.UnitPrice = unitPrice;
            saleItem.Id = id;
            saleItem.ProductId = productId;
            saleItem.ProductSaleId = productSaleId;
            return saleItem;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NumSold
        {
            get
            {
                return _NumSold;
            }
            set
            {
                OnNumSoldChanging(value);
                ReportPropertyChanging("NumSold");
                _NumSold = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NumSold");
                OnNumSoldChanged();
            }
        }
        private global::System.Int32 _NumSold;
        partial void OnNumSoldChanging(global::System.Int32 value);
        partial void OnNumSoldChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime ExDate
        {
            get
            {
                return _ExDate;
            }
            set
            {
                OnExDateChanging(value);
                ReportPropertyChanging("ExDate");
                _ExDate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ExDate");
                OnExDateChanged();
            }
        }
        private global::System.DateTime _ExDate;
        partial void OnExDateChanging(global::System.DateTime value);
        partial void OnExDateChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal UnitPrice
        {
            get
            {
                return _UnitPrice;
            }
            set
            {
                OnUnitPriceChanging(value);
                ReportPropertyChanging("UnitPrice");
                _UnitPrice = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("UnitPrice");
                OnUnitPriceChanged();
            }
        }
        private global::System.Decimal _UnitPrice;
        partial void OnUnitPriceChanging(global::System.Decimal value);
        partial void OnUnitPriceChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Guid _Id;
        partial void OnIdChanging(global::System.Guid value);
        partial void OnIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductId
        {
            get
            {
                return _ProductId;
            }
            set
            {
                OnProductIdChanging(value);
                ReportPropertyChanging("ProductId");
                _ProductId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductId");
                OnProductIdChanged();
            }
        }
        private global::System.Guid _ProductId;
        partial void OnProductIdChanging(global::System.Guid value);
        partial void OnProductIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Guid ProductSaleId
        {
            get
            {
                return _ProductSaleId;
            }
            set
            {
                OnProductSaleIdChanging(value);
                ReportPropertyChanging("ProductSaleId");
                _ProductSaleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ProductSaleId");
                OnProductSaleIdChanged();
            }
        }
        private global::System.Guid _ProductSaleId;
        partial void OnProductSaleIdChanging(global::System.Guid value);
        partial void OnProductSaleIdChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SaleItem_Product", "Product")]
        public Product Product
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.SaleItem_Product", "Product").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.SaleItem_Product", "Product").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Product> ProductReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Product>("Model1.SaleItem_Product", "Product");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Product>("Model1.SaleItem_Product", "Product", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("Model1", "SaleItem_ProductSale", "ProductSale")]
        public ProductSale ProductSale
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductSale>("Model1.SaleItem_ProductSale", "ProductSale").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductSale>("Model1.SaleItem_ProductSale", "ProductSale").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<ProductSale> ProductSaleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<ProductSale>("Model1.SaleItem_ProductSale", "ProductSale");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<ProductSale>("Model1.SaleItem_ProductSale", "ProductSale", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
